# lightning.pytorch==2.0.3
seed_everything: 2258173030
trainer:
  accelerator: gpu
  precision: 32-true
  max_epochs: 50
  check_val_every_n_epoch: 1
  log_every_n_steps: 1
  gradient_clip_val: 2
  gradient_clip_algorithm: norm
  deterministic: true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: cnn
      project: trams-audio-classification
      log_model: all
      job_type: training
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        save_top_k: 3
        filename: val_loss-{epoch}-{step}-{val_loss:.2f}
        mode: min
    - class_path: lightning.pytorch.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 0.005
        device: cuda
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CyclicLR
  init_args:
    base_lr: 0.001
    max_lr: 0.01
    step_size_up: 25
    cycle_momentum: false
model:
  config:
    conv_size_base: 8
    conv_size_multiplier: 2
    num_blocks: 4
    kernel_size: 3
    stride: 2
    padding: 1
    kaiming_init_a: 0.1
    num_channels: 1
    num_classes: 9
    learning_rate: 0.0005
data:
  batch_size: 64
  validation_split: 0.1
  max_length_secs: 4
  snr: 5
  use_cache: False
ckpt_path:
